"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""


import os
from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
try:
    from dotenv import load_dotenv
except Exception:  # pragma: no cover - deployment resilience
    load_dotenv = None

# Load .env for local/dev only when python-dotenv is available.
if load_dotenv is not None:
    load_dotenv(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-k87*u8p&=#9_sf3b#q-h-hj-ds4^7yjl)!eq+e%lu2u)jcdnx$'
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY", "django-insecure-local-development-fallback"
)

# SECURITY WARNING: don't run with debug turned on in production!
# Accepts "True"/"true"/"1"/"yes" — any other value (including "False" as a
# string) is treated as False so production env vars behave as expected.
DEBUG = os.environ.get("DEBUG", "False").lower() in ("1", "true", "yes")

# Behind managed proxies (Render, Railway, Nginx) the TLS terminator sets this.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Domains that are allowed to serve this Django application.
# When self-hosting, append your domains via DJANGO_ALLOWED_HOSTS,
# e.g. "sacco.example.com,sacco-api.onrender.com"
ALLOWED_HOSTS = [
    "isaactech.pythonanywhere.com",
    "localhost",
    "127.0.0.1",
    "[::1]",
    # Arena / E2B live-preview hosts (e.g. https://8000-<sandbox-id>.e2b.app)
    ".e2b.app",
] + [
    host.strip()
    for host in os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")
    if host.strip()
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # my apps
    'users.apps.UsersConfig',
    'customers.apps.CustomersConfig',
    'members.apps.MembersConfig',
    "accounts.apps.AccountsConfig",
    "loans.apps.LoansConfig",

    # Third party apps
    'rest_framework',
    "corsheaders",
    'rest_framework_simplejwt',

    # Added in MGR001
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serve static files (admin, browsable API) directly without Nginx.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
#
# Local Python development should work without a running database service, so it
# defaults to SQLite. Docker Compose sets DATABASE_MODE=postgres explicitly.
# Set DATABASE_MODE=postgres locally only when you deliberately want to connect
# to a locally running PostgreSQL instance.
DATABASE_MODE = os.getenv("DATABASE_MODE", "sqlite").lower()

if DATABASE_MODE == "sqlite":
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / os.getenv("SQLITE_DATABASE_NAME", "db.sqlite3"),
        }
    }
elif DATABASE_MODE in {"postgres", "postgresql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("DATABASE_NAME", "open-sacco-db"),
            "USER": os.getenv("DATABASE_USERNAME", "admin"),
            "PASSWORD": os.getenv("DATABASE_PASSWORD", "password"),
            "HOST": os.getenv("DATABASE_HOST", "127.0.0.1"),
            "PORT": os.getenv("DATABASE_PORT", "5432"),
        }
    }
else:
    raise ValueError("DATABASE_MODE must be either 'sqlite' or 'postgres'.")

# Managed hosts (Render, Railway, Heroku-style, Neon) hand out a single
# DATABASE_URL. When present it overrides DATABASE_MODE entirely.
DATABASE_URL = os.environ.get("DATABASE_URL")
if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        "default": dj_database_url.parse(
            DATABASE_URL, conn_max_age=600, ssl_require=not DEBUG
        )
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# media file configurations
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")

DEFAULT_CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://open-sacco.vercel.app",
]

# Keep the deployed frontend origin explicit.  Do not read this value from the
# environment: a stale CORS_ALLOWED_ORIGINS variable on the host would replace
# this list and make the API fail browser preflight requests.
CORS_ALLOWED_ORIGINS = DEFAULT_CORS_ALLOWED_ORIGINS

# When self-hosting, add your frontend origin(s) here instead of editing code,
# e.g. CORS_EXTRA_ORIGINS="https://sacco.example.com,https://my-app.vercel.app"
_EXTRA_ORIGINS = [
    origin.strip()
    for origin in os.environ.get("CORS_EXTRA_ORIGINS", "").split(",")
    if origin.strip()
]
CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS + _EXTRA_ORIGINS

# Required for unsafe methods (POST/PUT/PATCH/DELETE) when CSRF checks are in play.
CSRF_TRUSTED_ORIGINS = [
    "https://open-sacco.vercel.app",
    # Arena / E2B live-preview hosts
    "https://*.e2b.app",
] + _EXTRA_ORIGINS

# Covers Vercel preview deployments like https://open-sacco-git-branch.vercel.app
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
    # Arena / E2B live-preview hosts
    r"^https://.*\.e2b\.app$",
]

REST_FRAMEWORK = {
    'COERCE_DECIMAL_TO_STRING': False,
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

# Simple JWT
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
    "TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSerializer",
    "TOKEN_VERIFY_SERIALIZER": "rest_framework_simplejwt.serializers.TokenVerifySerializer",
    "TOKEN_BLACKLIST_SERIALIZER": "rest_framework_simplejwt.serializers.TokenBlacklistSerializer",
    "SLIDING_TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainSlidingSerializer",
    "SLIDING_TOKEN_REFRESH_SERIALIZER": "rest_framework_simplejwt.serializers.TokenRefreshSlidingSerializer",
}

# Loan eligibility settings. These are warnings for staff review, never an
# automatic rejection of a loan application.
LOAN_MINIMUM_MEMBERSHIP_MONTHS = int(
    os.getenv("LOAN_MINIMUM_MEMBERSHIP_MONTHS", "3")
)
LOAN_MINIMUM_MONTHLY_CONTRIBUTION = os.getenv(
    "LOAN_MINIMUM_MONTHLY_CONTRIBUTION", "0.00"
)

AUTH_USER_MODEL = "users.User"
# No append slash at the end of URL
# APPEND_SLASH = True

# --------------------------------------------------------------------------
# Production security — applies automatically when DEBUG is off.
# --------------------------------------------------------------------------
if not DEBUG:
    SECURE_SSL_REDIRECT = os.environ.get("SECURE_SSL_REDIRECT", "True").lower() in ("1", "true", "yes")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

# --------------------------------------------------------------------------
# M-Pesa (Safaricom Daraja) — get sandbox keys at developer.safaricom.co.ke
# Leave blank to keep the integration disabled; the API then answers 503 with
# a clear "not configured" message instead of crashing.
# --------------------------------------------------------------------------
MPESA_ENVIRONMENT = os.environ.get("MPESA_ENVIRONMENT", "sandbox")  # or "production"
MPESA_CONSUMER_KEY = os.environ.get("MPESA_CONSUMER_KEY", "")
MPESA_CONSUMER_SECRET = os.environ.get("MPESA_CONSUMER_SECRET", "")
MPESA_SHORTCODE = os.environ.get("MPESA_SHORTCODE", "")
MPESA_PASSKEY = os.environ.get("MPESA_PASSKEY", "")
MPESA_CALLBACK_URL = os.environ.get("MPESA_CALLBACK_URL", "")

